// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bubnjokfdwhblqjfnbki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Ym5qb2tmZHdoYmxxamZuYmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDUyODYsImV4cCI6MjA3MTI4MTI4Nn0.1jZkXoAeK3ZEe8Lc42SnjZXg0rF5LyGT-2dWLRFJUsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});